/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Control_LEDs                           */
/*      FILE         :  Control_LEDs.c                         */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX62N                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                


#include "iodefine.h"
#include "config.h"

int main(void)
{

	ENABLE_LEDS;
	ENABLE_SWITCHES;
	PORT4.ICR.BYTE = 0xFF;

	while(1)
	{
		if (SW1_PRESSED == 0)
		{
			GREEN_LEDS = 0;

		}
		else if (SW2_PRESSED == 0)
		{
			RED_LEDS = 0;

		}
		else if (SW3_PRESSED == 0)
		{
			ALL_LEDS_ON;
		}
		else
		{
			ALL_LEDS_OFF;
		}

	}
	return 0;
}
